name: Keep Alive
on:
  schedule:
    # At 00:00 on day-of-month 1.
    - cron: "0 0 1 * *"
permissions:
  actions: write
jobs:
  cronjob-based-github-action:
    name: Keep Alive
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2 # using the workflow with default settings
